debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: pass
  jpa:
#    database: mysql   # 추가 해준 부분
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 추가 해준 부분
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always

#---
#
#spring:
#  config.activate.on-profile: test
#  datasource.url: jdbc:h2:mem:testdb